"use client";
import { useState } from "react";
import type { ScenarioReview } from "./validationLabTypes";

export default function HumanReviewPanel({ scenarioId, runId, reviews, onChanged }: { scenarioId: string; runId: string | null; reviews: ScenarioReview[]; onChanged: () => void }) {
  const [reviewType, setReviewType] = useState("SUBJECT_MATTER"); const [decision, setDecision] = useState("APPROVED"); const [notes, setNotes] = useState(""); const [error, setError] = useState<string | null>(null);
  const save = async () => { const res = await fetch(`/api/admin/recruitment/scenarios/${scenarioId}/reviews`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ validationRunId: runId, reviewType, decision, notes }) }); const body = await res.json().catch(() => ({})); if (!res.ok) return setError(body.error || "Could not save review"); setNotes(""); setError(null); onChanged(); };
  return <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-uq bg-uq-elev1 p-4"><h3 className="font-semibold text-uq">Record human review</h3><p className="mt-1 text-xs text-uq-3">Review roles remain separate even when performed by one authorised user.</p><select value={reviewType} onChange={(e) => setReviewType(e.target.value)} className="mt-3 block w-full rounded-md border border-uq bg-uq-elev2 px-3 py-2 text-sm"><option value="SUBJECT_MATTER">Subject-matter review</option><option value="ASSESSMENT_DESIGN">Assessment-design review</option><option value="ACCESSIBILITY">Accessibility review</option></select><select value={decision} onChange={(e) => setDecision(e.target.value)} className="mt-2 block w-full rounded-md border border-uq bg-uq-elev2 px-3 py-2 text-sm"><option value="APPROVED">Approved</option><option value="CHANGES_REQUIRED">Changes required</option><option value="APPROVED_WITH_LIMITATIONS">Approved with documented limitations</option></select><textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={4} placeholder="Evidence considered, limitations, and rationale" className="mt-2 block w-full rounded-md border border-uq bg-uq-elev2 px-3 py-2 text-sm" />{error && <p className="mt-2 text-xs text-uq-danger-text">{error}</p>}<button onClick={() => void save()} disabled={!runId || !notes.trim()} className="mt-3 rounded-lg bg-uq-accent px-4 py-2 text-sm text-[color:var(--uq-text-on-accent)] disabled:opacity-50">Save review</button></section><section><h3 className="font-semibold text-uq">Review history</h3><div className="mt-3 space-y-2">{reviews.length === 0 ? <p className="text-sm text-uq-3">No human reviews recorded.</p> : reviews.map((review) => <article key={review.id} className="rounded-xl border border-uq bg-uq-elev1 p-3 text-xs"><div className="font-mono uppercase text-uq-3">{review.reviewType.replace(/_/g, " ")} · {review.decision.replace(/_/g, " ")}</div><p className="mt-2 whitespace-pre-wrap text-uq-2">{review.notes}</p><time className="mt-2 block font-mono text-[10px] text-uq-3">{new Date(review.createdAt).toLocaleString()}</time></article>)}</div></section></div>;
}
